min_particles: 500
max_particles: 2000

kld_err: 0.05
kld_z: 0.99

update_min_d: 0.20
update_min_a: 0.20

resample_interval: 1

transform_tolerance: 1.0

recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

laser_max_beams: 60

odom_model_type: diff

odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2

laser_model_type: likelihood_field

laser_z_hit: 0.95
laser_z_rand: 0.05

laser_sigma_hit: 0.2
laser_likelihood_max_dist: 2.0

base_frame_id: p3dx_tf/base_link
odom_frame_id: p3dx_tf/odom
global_frame_id: map
laser_frame_id: p3dx_tf/lms100